export const TOPICS = [
  ['Arrays & Hashing', ['Contains Duplicate','Valid Anagram','Two Sum','Group Anagrams','First Missing Positive'], ['contains-duplicate','valid-anagram','two-sum','group-anagrams','first-missing-positive']],
  ['Two Pointers', ['Valid Palindrome','Merge Sorted Array','Reverse String','3Sum','Trapping Rain Water'], ['valid-palindrome','merge-sorted-array','reverse-string','3sum','trapping-rain-water']],
  ['Sliding Window', ['Best Time to Buy and Sell Stock','Maximum Average Subarray I','Contains Duplicate II','Longest Substring Without Repeating Characters','Minimum Window Substring'], ['best-time-to-buy-and-sell-stock','maximum-average-subarray-i','contains-duplicate-ii','longest-substring-without-repeating-characters','minimum-window-substring']],
  ['Stack', ['Valid Parentheses','Baseball Game','Implement Stack using Queues','Evaluate Reverse Polish Notation','Largest Rectangle in Histogram'], ['valid-parentheses','baseball-game','implement-stack-using-queues','evaluate-reverse-polish-notation','largest-rectangle-in-histogram']],
  ['Binary Search', ['Binary Search','Search Insert Position','First Bad Version','Search in Rotated Sorted Array','Median of Two Sorted Arrays'], ['binary-search','search-insert-position','first-bad-version','search-in-rotated-sorted-array','median-of-two-sorted-arrays']],
  ['Linked List', ['Reverse Linked List','Merge Two Sorted Lists','Linked List Cycle','Add Two Numbers','Merge k Sorted Lists'], ['reverse-linked-list','merge-two-sorted-lists','linked-list-cycle','add-two-numbers','merge-k-sorted-lists']],
  ['Trees', ['Maximum Depth of Binary Tree','Invert Binary Tree','Same Tree','Binary Tree Level Order Traversal','Binary Tree Maximum Path Sum'], ['maximum-depth-of-binary-tree','invert-binary-tree','same-tree','binary-tree-level-order-traversal','binary-tree-maximum-path-sum']],
  ['Heap / Priority Queue', ['Kth Largest Element in a Stream','Last Stone Weight','Relative Ranks','Kth Largest Element in an Array','Find Median from Data Stream'], ['kth-largest-element-in-a-stream','last-stone-weight','relative-ranks','kth-largest-element-in-an-array','find-median-from-data-stream']],
  ['Recursion & Backtracking', ['Fibonacci Number','Power of Two','Add Digits','Subsets','N-Queens'], ['fibonacci-number','power-of-two','add-digits','subsets','n-queens']],
  ['Graphs', ['Find Center of Star Graph','Find if Path Exists in Graph','Find the Town Judge','Number of Islands','Word Ladder'], ['find-center-of-star-graph','find-if-path-exists-in-graph','find-the-town-judge','number-of-islands','word-ladder']],
  ['Matrix', ['Transpose Matrix','Reshape the Matrix','Flood Fill','Rotate Image','Word Search II'], ['transpose-matrix','reshape-the-matrix','flood-fill','rotate-image','word-search-ii']],
  ['Dynamic Programming', ['Climbing Stairs','House Robber','Min Cost Climbing Stairs','Coin Change','Regular Expression Matching'], ['climbing-stairs','house-robber','min-cost-climbing-stairs','coin-change','regular-expression-matching']],
  ['Greedy', ['Best Time to Buy and Sell Stock II','Assign Cookies','Lemonade Change','Jump Game','Candy'], ['best-time-to-buy-and-sell-stock-ii','assign-cookies','lemonade-change','jump-game','candy']],
  ['Intervals', ['Summary Ranges','Maximum Population Year','Merge Similar Items','Merge Intervals','Data Stream as Disjoint Intervals'], ['summary-ranges','maximum-population-year','merge-similar-items','merge-intervals','data-stream-as-disjoint-intervals']],
  ['Math & Bit Manipulation', ['Single Number','Number of 1 Bits','Missing Number','Sum of Two Integers','Maximum XOR of Two Numbers in an Array'], ['single-number','number-of-1-bits','missing-number','sum-of-two-integers','maximum-xor-of-two-numbers-in-an-array']]
].map(([name, names, slugs]) => ({ name, questions: names.map((title, i) => ({ title, slug: slugs[i], difficulty: i < 3 ? 'Easy' : i === 3 ? 'Medium' : 'Hard' })) }));
